apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab
  template:
    metadata:
      labels:
        app: lab
    spec:
      containers:
      - name: server1-container
        image: gcr.io/[project_id]/[imagen]
        ports:
        - containerPort: 3000
      - name: server2-containter
        image: gcr.io/pure-advantage-305004/server1p2
        ports:
        - containerPort: 3001