apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-py2
  template:
    metadata:
      labels:
        app: kafka-py2
    spec:
      containers:
      - name: zookeeper
        image: wurstmeister/zookeeper:3.4.6
        ports:
        - containerPort: 2181
        #expose:
        #- "2181"
        #restart: always
        #container_name: zookeeper

      - name: kafka
        image: wurstmeister/kafka:2.12-2.3.0
        #depends_on:
        #  - zookeeper
        ports:
        - containerPort: 9092
        - containerPort: 9093
        #ports:
        #  - "9093:9093"
        #expose:
        #  - "9092"
        env:
          - name: KAFKA_CREATE_TOPICS
            value: "sarama_topic:2:1"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: INSIDE://:9092,OUTSIDE://:9093
          #KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://35.192.47.92:9093
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
          - name: KAFKA_LISTENERS
            value: INSIDE://:9092,OUTSIDE://:9093
          #KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
          #KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://35.192.47.92:9093
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: :2181
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: INSIDE
        #restart: always
        #container_name: kafka

      - name: consumer
        #image: gcr.io/pure-advantage-305004/consumerkafka
        image: mickyxd/consumerkafka
        #ports:
        #- containerPort: 8000
      - name: producer
        #image: gcr.io/pure-advantage-305004/producerkafka
        image: mickyxd/producerkafka
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka-py2
  ports:
    - port: 8000
      targetPort: 8000
      #nodePort: 31000
  #type: LoadBalancer
  type: NodePort