version: '3.0'
services:

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    expose:
      - "2181"
    restart: always
    container_name: zookeeper

  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    expose:
      - "9092"
    environment:
      KAFKA_CREATE_TOPICS: "sarama_topic:2:1"
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      #KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://35.192.47.92:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://localhost:9093
      #KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      #KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://35.192.47.92:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    restart: always
    container_name: kafka


---
  containers:
    - name: zookeeper
      image: wurstmeister/zookeeper:3.4.6
      ports:
      - containerPort: 2181
      #expose:
      #- "2181"
      #restart: always
      #container_name: zookeeper

    - name: kafka
      image: wurstmeister/kafka:2.12-2.3.0
      #depends_on:
      #  - zookeeper
      ports:
      - containerPort: 9092
      - containerPort: 9093
      #ports:
      #  - "9093:9093"
      #expose:
      #  - "9092"
      env:
        - name: KAFKA_CREATE_TOPICS
          value: "sarama_topic:2:1"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: INSIDE://kafka:9092,OUTSIDE://localhost:9093
        #KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://35.192.47.92:9093
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
        - name: KAFKA_LISTENERS
          value: INSIDE://0.0.0.0:9092,OUTSIDE://localhost:9093
        #KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
        #KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://35.192.47.92:9093
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: INSIDE
      #restart: always
      #container_name: kafka