apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis-pub-container
        image: gcr.io/pure-advantage-305004/redis-pub
        ports:
        - containerPort: 8000
      - name: redis-sub-container
        image: gcr.io/pure-advantage-305004/redis-sub